### ISSUE TITLE
How to stop  clean_rawdata deleting channels？

### ISSUE THREAD

**Issue by Tonshy** [sccn/clean_rawdata#10]
Hello ，I recently confront a problem. When I use clean_rawdata, it tends to delete one or two channels of the data,  whitch affect my following processing( I need all channels ) . Any way I can handle this?

**Comment by arnodelorme** [comment]
If you use the interface you can unclick the second checkbox and it will not delete channels. There are 3 options for deleting channels (noise, correlation, flat), and you need to set all of these options to off (which the interface will do). You can also look at the EEGLAB history for the call.
