### ISSUE TITLE
`asr_process` silently skips processing if insufficient memory

### ISSUE THREAD

**Issue by chriscline** [sccn/clean_rawdata#12]
In `asr_process.m`, the number of splits are calculated with the line:

	splits = ceil((C*C*S*8*8 + C*C*8*S/stepsize + C*S*8*2 + S*8*5) / (maxmem*1024*1024 - C*C*P*8*3));

However, the denominator can be negative if `maxmem` indicates there is insufficient memory. The following `for i=1:splits` loop is then skipped entirely and no processing is done, without any error or warning being printed.

**Comment by chkothe** [comment]
That's a good find!

**Comment by arnodelorme** [comment]
I have added an error if the denominator is negative.
