### ISSUE TITLE
ASR visualization issue

### ISSUE THREAD

**Issue by linaismail** [sccn/clean_rawdata#13]
Dear all,
As I am new in using MATLAB and especially EEGLAB, I have followed all instructions for applying the clean_rawdat, however I can not visualize the original and new data at all. I received the following output in the command window
"Use vis_artifacts to compare the cleaned data to the original.
Warning: vis_artifacts failed. Skipping visualization. 
> In pop_clean_rawdata (line 151) "

can anyone help me fix the issue, simply?

**Comment by barlehmann** [comment]
I am also running into the same issue, and am also new to EEGLAB and Matlab. It seems that the issue has been closed, but I am not sure where to find the answer to this question, as I am having the same issue. Any tips would be greatly appreciated.
