### ISSUE TITLE
clean_rawdata and -nojvm

### ISSUE THREAD

**Issue by behinger** [sccn/clean_rawdata#18]
Hi!
I cant run clean_rawdata in headless matlab mode using matlab -nojvm (-nodesktop still takes one "virtual" slot of the X which are capped at 75 at least for me).

The reason is this line:
hlp_memfree, which calls a java function to get free memory.
https://github.com/sccn/clean_rawdata/blob/591ed754ae04d420fa4aa96d9ed482380232b4e6/asr_calibrate_r.m#L276

Which I cannot overwrite in `asr_calibrate`, but it is correctly skipped in other functions e.g. `asr_process_r`.

I think the bug is, that `asr_calibrate` never receives the `maxmem` option.

(minor: maybe refactor that helper function given that it is defined again in `asr_process_r`)

Best, Bene

Edit: I got confused, it is asr_calibrate not asr_calibrate_r (or maybe both? whats the difference except one is in private the other not?). 
Edit Edit: I just got notice that there is "nodesktop" and "nodisplay", which fixes the problem for me. The bug still exists though

**Comment by arnodelorme** [comment]
I have fixed the problem in 0a9045a (just assigned a fixed amount of RAM)
