### ISSUE TITLE
ASR with low number of channels

### ISSUE THREAD

**Issue by vpKumaravel** [sccn/clean_rawdata#19]
Dear Arno & team,

This is out of curiosity, I wonder if ASR was tested on a low-density EEG setup such as (8, or 16) and what are the implications, in that case?

In general, is there any guideline for the number of optimal channels that ASR would require to function in its fullest?

Thank you so much,

Velu

**Comment by arnodelorme** [comment]
Yes, no more than less channels when using ASR is the common recommendation. Best

**Comment by vpKumaravel** [comment]
Thanks, Arno!

Sorry, but the message is not clear to me.

**Comment by arnodelorme** [comment]
Sorry I meant, not less than 4 channels when using ASR. So 8 to 16 should be perfectly fine.
