### ISSUE TITLE
"Reject data using Clean Rawdata and ASR" not available

### ISSUE THREAD

**Issue by sayakakidby** [sccn/clean_rawdata#21]
Hi there, 

I am using EEGLAB v2019.1 on MATLAB 2017b, and wanted to use “Reject data using Clean Rawdata and ASR”.
I’m attaching the screenshot but I can’t seem to select it whichever data I upload, epoched or continuous.
Is this a bug, or is there anything wrong with my data? 
I updated my EEGLAB to v2021.0 but the issue remains. I also tried using it on MATLAB 2019.b but no luck. 

Thanks for your help in advance! 

<img width="568" alt="eeglab_error" src="https://user-images.githubusercontent.com/61603836/110918928-9dcce400-8313-11eb-8b73-8edd81d40dab.png">

**Comment by arnodelorme** [comment]
Did you clone EEGLAB from the web? You need to clone EEGLAB with submodules as indicated on the README.md file. Or you can install the cleanrawdata plugin from the EEGLAB plugin managers.

**Comment by sayakakidby** [comment]
Hi Arno, 

Thank you very much for your comment, and I am so sorry for the delay in my response. 
I clone EEGLAB from Github with submodules (I think) but the option is not available still. I installed the cleanrawdata plugin and can see it's been added (please see the screenshot) but still when I go to Tools I can't see the Clean Raw data function as available either.  

![Screenshot 2021-03-18 at 14 48 26](https://user-images.githubusercontent.com/61603836/111645889-11319280-87f9-11eb-8b0d-cebe49ce145c.png)


Is there anything else I could try? So sorry to trouble you!

**Comment by arnodelorme** [comment]
Maybe it is greyed out because you have loaded epoched data not continuous data.

<img width="445" alt="Screen Shot 2021-03-18 at 6 41 10 AM" src="https://user-images.githubusercontent.com/1872705/111663569-094fff00-87b5-11eb-9683-76f86fba493b.png">
