### ISSUE TITLE
Inconsistent results using ASR

### ISSUE THREAD

**Issue by krishnamaiya** [sccn/clean_rawdata#24]
Dear all,
Initially I have used "clean raw data using ASR" with default values. Different number of channels were rejected and different duration of clean data were obtained in multiple run of same dataset. Later, manually I have removed bad channel and removed bad segment through "Automatic continuous rejection". Faced same problem as earlier. So I m getting inconsistent results for same data set for multiple run. 
Kindly help me in this regard.
Thanks in advance.

**Comment by arnodelorme** [comment]
Can you try

Are you using the latest version. We fixed an issue related to reproducibility. 
Also try
rng(‘default’) before you run it.

Arno

**Comment by krishnamaiya** [comment]
Dear Arno,

Thanks a lot for your valuable reply. I m using ASR v2.3 and EEGLab v2019.0 versions. Probably this is the old version as you mentioned. Would you suggest the latest version optimal for ASR, since I m using Matlab 2018a. I need to check all these compatibilities too. 
second point you mentioned "rng('default), you mean to say I need to run this command in matlab command window before I proceed with ASR for all dataset?

Thanks in advance.

**Comment by arnodelorme** [comment]
Yes, I would rig(‘default’) before every dataset.

**Comment by arnodelorme** [comment]
I have changed the code to use reset rng in some of the code.
