### ISSUE TITLE
When 'eeglab' is called before running clean_rawdata(), the output changes.

### ISSUE THREAD

**Issue by MakotoMiyakoshi** [sccn/clean_rawdata#27]
I received the following user report on July 5, 2021: "These suggested to me that ASR performs well, but when I kept digging the problem I found a way to reproduce the bug. If I initialize eeglab before first computation and then run clean_rawdata(), I get stable results no matter how many runs it does. But a simple call of 'eeglab' command before every computation changes the behavior dramatically."

**Comment by arnodelorme** [comment]
I have added code to seed the random number in rasr_nonlinear_eigenspace. This is all I can think of. Let me know if the problem persist.
