### ISSUE TITLE
excluding the externals from being impacted by the function

### ISSUE THREAD

**Issue by DouweHorsthuis** [sccn/clean_rawdata#28]
Hi,
 I was wondering if there is a way to specifically not have externals included in this function. I want to be able to reference back later to these, but I don't see a option to add a channel range. 
As an example I used to use EEG = pop_rejchan(EEG,'elec', [1:160],'threshold',5,'norm','on','measure','kurt');

But I would prefer to use the clean_artifacts function for this.

Thank you!
Douwe

**Comment by arnodelorme** [comment]
We have implemented the fix

**Comment by DouweHorsthuis** [comment]
Fantastic, thank you so much!

**Comment by DouweHorsthuis** [comment]
Good afternoon,
I am currently using EEGLAB V2021.1 and the latest available update (V2.6) of clean_rawdata. And even though it is indeed possible to select a subset of channels. I always get an error after the data is cleaned, or it simply doesn't delete bad channels. 

When I leave all the settings as is, and select all 64channels except for the 8 externals I get the following error:
![image](https://user-images.githubusercontent.com/64816053/164308626-de7fc5bc-0ac5-467b-8fd3-3e1aa8c2b8ab.png)
(in case it doesn't show it says "Issue with adding back channels removed. Send us your data., This is not a bug (Error occurred in fuction clean_artifacts() at line 298)

To be sure this wasn't something on my side I uninstalled EEGLAB and re-downloaded a fresh one (v2021.1) and updated clean_raw to the last version. In this case:

If I only include the options to delete bad channels, and select 64 chns without externals it gives me the following error

![image](https://user-images.githubusercontent.com/64816053/164311402-44ea23ef-0732-4274-9959-41baeb3be29f.png)

However, if I run it using all the cleaning functions as they are selected through the gui, it runs without an error. However, even though it says in the command window that channels are being deleted, all 72 channels exist at the end. 

Please let me know if there is anything I can do to stop this issue.
Thank you for your time,
Douwe

**Comment by MTSVis** [comment]
> Good afternoon, I am currently using EEGLAB V2021.1 and the latest available update (V2.6) of clean_rawdata. And even though it is indeed possible to select a subset of channels. I always get an error after the data is cleaned, or it simply doesn't delete bad channels.
> 
> When I leave all the settings as is, and select all 64channels except for the 8 externals I get the following error: ![image](https://user-images.githubusercontent.com/64816053/164308626-de7fc5bc-0ac5-467b-8fd3-3e1aa8c2b8ab.png) (in case it doesn't show it says "Issue with adding back channels removed. Send us your data., This is not a bug (Error occurred in fuction clean_artifacts() at line 298)
> 
> To be sure this wasn't something on my side I uninstalled EEGLAB and re-downloaded a fresh one (v2021.1) and updated clean_raw to the last version. In this case:
> 
> If I only include the options to delete bad channels, and select 64 chns without externals it gives me the following error
> 
> ![image](https://user-images.githubusercontent.com/64816053/164311402-44ea23ef-0732-4274-9959-41baeb3be29f.png)
> 
> However, if I run it using all the cleaning functions as they are selected through the gui, it runs without an error. However, even though it says in the command window that channels are being deleted, all 72 channels exist at the end.
> 
> Please let me know if there is anything I can do to stop this issue. Thank you for your time, Douwe

Having the same problem with EGI data.

**Comment by DouweHorsthuis** [comment]
I tried it right after the 2022 update and it didn't work for me then, haven't tried it since
