### ISSUE TITLE
vis_artifacts compatibility issue between matlab versions

### ISSUE THREAD

**Issue by crisglav** [sccn/clean_rawdata#29]
Dear developers,

I am using vis_artifacts to check data before and after preprocessing. I can run vis_artifacts in matlab R2020b without any problem, however, when I run it in matlab R2020a I get into an error because the scale variable in line 220 is defined as a row vector instead of column vector in 2020a.
https://github.com/sccn/clean_rawdata/blob/5171ad6da8860e2e8348f82dd25a452e93efc6ea/vis_artifacts.m#L220
 That affects repmat() two lines later. I would suggest to include
`scale = scale(:);`
just before line 222 to make `scale `a column vector and ensure compatibility with earlier versions of matlab.
Thank you very much!
Cristina Gil

**Comment by chkothe** [comment]
Fixed
