### ISSUE TITLE
Error in pop_clean_rawdata when calling multiple datasets

### ISSUE THREAD

**Issue by crisglav** [sccn/clean_rawdata#31]
When I try to run pop_clean_rawdata with multiple datasets as input I get an error in:
https://github.com/sccn/clean_rawdata/blob/26c6ded050b25bbdad3a3ebba121dbe7b95ac627/pop_clean_rawdata.m#L136
because clean_artifacts is given as an input handle instead of a string to eeg_eval().

I would suggest changing lines 134 and 136 to:
`[ EEG, com ] = eeg_eval( 'clean_artifacts', EEG, 'warning', 'on', 'params', options );`
and
`[ EEG, com ] = eeg_eval( 'clean_artifacts', options );`
respectively.

I am using the most recent version of clean_rawdata and eeglab2021 in matlab R2020b.
Best,
Cristina Gil

**Comment by behinger** [comment]
Edit: - sorry nevermind, that fix is perfectly fine, I changed something in the eeg_eval function

**Comment by arnodelorme** [comment]
We made the change. This is because you have an old version of MATLAB though. New versions of MATLAB can handle function pointers.
