### ISSUE TITLE
Unable to see artifact visualization

### ISSUE THREAD

**Issue by barlehmann** [sccn/clean_rawdata#34]
I keep trying to use the pop_clean_rawdata and have even copied the latest 2.6 version but continue to get errors when trying to use it for viewing the artifacts that have been edited. I thought the issue might be that the dataset I am using has 20 channels but when I pick out both the 20 as well as the 19 subset, neither allows this to work. 

Specifically I get: 
Warning: vis_artifacts failed. Skipping visualization. 
> In pop_clean_rawdata (line 158) 

Any insight/suggestions would be greatly appreciated. TIA. Also, please let me know if this is not appropriate to list this issue here, or in another place, I apologize if this is not the place to do so.

**Comment by arnodelorme** [comment]
Sorry for the late answer. We would need to see your data and what you are trying to do. Would you mind sharing your data and instructions on reproducing the issue?

**Comment by guoyongjian111** [comment]
![image](https://user-images.githubusercontent.com/82032571/163704394-07899b1b-4c0c-43ee-90d3-4b69e4a4f1dc.png)
I have the same problem，And I want to know whether clean_rawdata is no longer used after the epoch, such as resting eeg data after the epoch in two seconds。

**Comment by arnodelorme** [comment]
Can you share your data?

Yes, clean_rawdata is for continuous data.

**Comment by guoyongjian111** [comment]
> Can you share your data?
> 
> Yes, clean_rawdata is for continuous data.

my matlab version is 2021b,eeglabv2022.0, clean_rawdata2.6

**Comment by guoyongjian111** [comment]
> 

https://drive.google.com/file/d/1VYrVqncTI7lL2xDpJdT1VPLBr1rwOvUJ/view?usp=sharing
this is a resting eeg data.

**Comment by arnodelorme** [comment]
The uncompressed file is not readable by EEGLAB.

**Comment by guoyongjian111** [comment]
> 

I know, but uploading is faster after compression. After decompression, it is my data.....

**Comment by JLULijh** [comment]
Dude, have you solved your problem? I have the same problem.

**Comment by arnodelorme** [comment]
Would you mind resending a file that generates the problem? I could not load the file before because it was corrupted.

**Comment by JLULijh** [comment]
Thanks for the reply, I've fixed this issue.


I tried it with the sample_set that came with eeglab.
The problem may be with the eeglab and ASR versions，I ended up successfully visualizing with older versions of eeglab and ASR2.7.


&nbsp;


李佳辉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arnaud ***@***.***&gt;; 
发送时间: 2023年3月3日(星期五) 凌晨3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sccn/clean_rawdata] Unable to see artifact visualization (Issue #34)





 
Would you mind resending a file that generates the problem? I could not load the file before because it was corrupted.

**Comment by arnodelorme** [comment]
This has been fixed. Let us know if it does not work for you.

**Comment by Marl1ne** [comment]
I have the same issue with some but not all of my data files. But by rejecting a small piece of data by eye before running the clean rawdata the visualization works. any idea why its doing so?

**Comment by arnodelorme** [comment]
If it does not work with the current version, can you upload a dataset and reopen the issue. This would be very much appreciated.
