### ISSUE TITLE
ASR burst criterion default threshold

### ISSUE THREAD

**Issue by d-scanzi** [sccn/clean_rawdata#35]
Hi there, 

In our lab we noticed that there is a discrepancy between the ASR default cutoff and the suggested "conservative" criterion reported in the [README](https://github.com/sccn/clean_rawdata/blob/master/README.md). Currently, the default criterion is set to 5 SD, but the one suggested is 10. 

A cutoff of 5 is very aggressive, and there is evidence that a value at least greater than 10 should be used to obtain a sensible reduction of artifacts without losing too much information ([Chang at al., 2018](https://www.researchgate.net/publication/325921646_Evaluation_of_Artifact_Subspace_Reconstruction_for_Automatic_EEG_Artifact_Removal), also referenced in the [wiki](https://github.com/sccn/clean_rawdata/wiki) section of this repository). 

Currently, the README file states:

*For new users it is recommended to first visually inspect the difference between the aw and the cleaned data (using eegplot) to get a sense of the content the is removed at various levels of this input variable. Here, a quite conservative value is 10; this is the current default value.*

This might throw off some users if they do not keep attention at the actual cut off. 

## Suggestions

- Set the default value for ASR at 10. Possibly even higher (maybe 20) to stay on the conservative side. As for the paper reported above, a cutoff of 10 would potentially modify just under 60% of the data. 
- Modify the help text of the functions that uses ASR (`clean_rawdata`, `clean_asr`, `clean_artifacts`) as they currently report the following: *For new users it is recommended to at first visually inspect the difference between the original and cleaned data to get a sense of the removed content at various levels. A quite conservative value is 5. Default: 5.* This might be another source of confusion, as 5 is said to be a conservative default, while it is actually aggressive. This help text should be updated independently of whether the default parameter is modified.

**Comment by arnodelorme** [comment]
Actually, the new default in the GUI is 20. I have updated the README file accordingly, as well as all the MATLAB files. 5 is an aggressive value and 20 is a conservative value.

**Comment by d-scanzi** [comment]
Thank you @arnodelorme!

Just for completeness, `asr_calibrate` and `asr_calibrate_r` have the same help text (sorry I just noticed now), so you might want to update those too. 

Thanks again
