### ISSUE TITLE
BUG - version 2.6-seeding the RNG in MATLAB 2020a

### ISSUE THREAD

**Issue by tiborauer** [sccn/clean_rawdata#36]
---------
      Error ID:
      ---------
      'MATLAB:rng:reseedLegacy'
      --------------
      Error Details:
      --------------
      Error using rng (line 99)
      The current random number generator is the legacy generator.  This is
      because you have executed a command such as rand('state',0), which activates
      MATLAB's legacy random number behavior.  You may not use RNG to reseed the
      legacy random number generator.
      
      Use rng('default') to reinitialize the random number generator to its
      startup configuration, or call RNG using a specific generator type, such as
      rng(seed,'twister').
      
      Error in rasr_nonlinear_eigenspace (line 59)
          rng(0); % seeds the random number generator to produce a predictable
          sequence of numbers

**Comment by arnodelorme** [comment]
Which version are you using? The current version uses rng(0) and works under MATLAB 2021b.
