### ISSUE TITLE
Sample indices to retain in Clean_windows.m function might be wrong

### ISSUE THREAD

**Issue by vpKumaravel** [sccn/clean_rawdata#6]
File: Clean_windows.m

Line 116: swz = sort(wz);

Since the Z-score values are sorted, the corresponding window indices also change. This change is probably not taken care of, leading to the wrong calculation of removed_samples (line 126). 

![asr_error](https://user-images.githubusercontent.com/48288235/72364502-edefec80-36f6-11ea-969f-a2503601fd3f.PNG)

Please confirm. Thanks.
Best,
Velu

**Comment by arnodelorme** [comment]
swz dimension seems to be (channel x window) so only channels get sorted not windows. Your comment might be right if there is only one channel. @chkothe would you mind to confirm?

**Comment by arnodelorme** [comment]
I have double checked that the code is correct so closing this report.
